package engine

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"
)

// Config represents the config.yaml schema persisted by the TUI wizard.
type Config struct {
	Version   string `yaml:"version"`
	CreatedAt string `yaml:"created_at"`
	UpdatedAt string `yaml:"updated_at"`
	CLIVersion string `yaml:"cli_version"`

	Ollama    OllamaConfig    `yaml:"ollama"`
	GPU       GPUConfig       `yaml:"gpu"`
	Ports     PortsConfig     `yaml:"ports"`
	Providers ProvidersConfig `yaml:"providers"`
	DevMode   bool            `yaml:"dev_mode"`
}

// OllamaConfig holds Ollama-related settings.
type OllamaConfig struct {
	Mode      string       `yaml:"mode"`       // docker | local | remote
	RemoteURL string       `yaml:"remote_url"` // only used when mode=remote
	Models    ModelsConfig `yaml:"models"`
}

// ModelsConfig holds selected model lists.
type ModelsConfig struct {
	LLM       []string `yaml:"llm"`
	Embedding []string `yaml:"embedding"`
}

// GPUConfig holds GPU detection results and overrides.
type GPUConfig struct {
	Profile      string `yaml:"profile"`       // nvidia | amd | intel | none
	AutoDetected bool   `yaml:"auto_detected"` // false if user overrode detection
}

// PortsConfig holds host port assignments.
type PortsConfig struct {
	Frontend  int `yaml:"frontend"`
	Backend   int `yaml:"backend"`
	Qdrant    int `yaml:"qdrant"`
	QdrantGRPC int `yaml:"qdrant_grpc"`
	Ollama    int `yaml:"ollama"`
}

// ProvidersConfig tracks which cloud providers are configured.
type ProvidersConfig struct {
	OpenAI     bool `yaml:"openai"`
	Anthropic  bool `yaml:"anthropic"`
	OpenRouter bool `yaml:"openrouter"`
}

// DefaultConfig returns a Config with sensible defaults.
func DefaultConfig() Config {
	now := time.Now().UTC().Format(time.RFC3339)
	return Config{
		Version:    "1",
		CreatedAt:  now,
		UpdatedAt:  now,
		CLIVersion: "dev",
		Ollama: OllamaConfig{
			Mode: "docker",
			Models: ModelsConfig{
				LLM:       []string{"qwen2.5:7b"},
				Embedding: []string{"nomic-embed-text"},
			},
		},
		GPU: GPUConfig{
			Profile:      "none",
			AutoDetected: true,
		},
		Ports: PortsConfig{
			Frontend:   3000,
			Backend:    8000,
			Qdrant:     6333,
			QdrantGRPC: 6334,
			Ollama:     11434,
		},
		Providers: ProvidersConfig{},
		DevMode:   false,
	}
}

// ReadConfig reads config.yaml from the given path.
func ReadConfig(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Config{}, fmt.Errorf("read config: %w", err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return Config{}, fmt.Errorf("parse config: %w", err)
	}

	return cfg, nil
}

// WriteConfig writes config.yaml to the given path.
func WriteConfig(path string, cfg Config) error {
	cfg.UpdatedAt = time.Now().UTC().Format(time.RFC3339)

	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}

	header := []byte("# config.yaml -- Generated by The Embedinator TUI. Do not edit manually.\n# Re-run `embedinator config` to modify settings.\n\n")
	content := append(header, data...)

	// Atomic write: write to temp, then rename.
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, content, 0644); err != nil {
		return fmt.Errorf("write config temp: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("rename config: %w", err)
	}

	return nil
}

// ValidateConfig checks a Config for required fields.
func ValidateConfig(cfg Config) error {
	switch cfg.Ollama.Mode {
	case "docker", "local", "remote":
		// valid
	default:
		return fmt.Errorf("invalid ollama.mode: %q (expected docker, local, or remote)", cfg.Ollama.Mode)
	}

	if cfg.Ollama.Mode == "remote" && cfg.Ollama.RemoteURL == "" {
		return fmt.Errorf("ollama.remote_url is required when mode=remote")
	}

	if len(cfg.Ollama.Models.LLM) == 0 {
		return fmt.Errorf("at least one LLM model must be selected")
	}
	if len(cfg.Ollama.Models.Embedding) == 0 {
		return fmt.Errorf("at least one embedding model must be selected")
	}

	switch cfg.GPU.Profile {
	case "nvidia", "amd", "intel", "none":
		// valid
	default:
		return fmt.Errorf("invalid gpu.profile: %q (expected nvidia, amd, intel, or none)", cfg.GPU.Profile)
	}

	if cfg.Ports.Frontend < 1024 || cfg.Ports.Frontend > 65535 {
		return fmt.Errorf("ports.frontend must be between 1024 and 65535")
	}
	if cfg.Ports.Backend < 1024 || cfg.Ports.Backend > 65535 {
		return fmt.Errorf("ports.backend must be between 1024 and 65535")
	}
	if cfg.Ports.Qdrant < 1024 || cfg.Ports.Qdrant > 65535 {
		return fmt.Errorf("ports.qdrant must be between 1024 and 65535")
	}
	if cfg.Ports.QdrantGRPC < 1024 || cfg.Ports.QdrantGRPC > 65535 {
		return fmt.Errorf("ports.qdrant_grpc must be between 1024 and 65535")
	}
	if cfg.Ports.Ollama < 1024 || cfg.Ports.Ollama > 65535 {
		return fmt.Errorf("ports.ollama must be between 1024 and 65535")
	}

	return nil
}

// ConfigExists checks whether config.yaml exists at the given path.
func ConfigExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
