package engine

import (
	"fmt"
	"os"
)

const localOllamaOverlayTemplate = `# docker-compose.local-ollama.yml
# Generated by The Embedinator TUI. Disables Docker Ollama and connects backend to host Ollama.
# Do not edit manually. Re-run 'embedinator config' to modify.

services:
  # Override ollama to be a no-op (satisfies depends_on)
  ollama:
    image: busybox:latest
    entrypoint: ["sh", "-c", "echo 'Ollama disabled (using local)' && sleep infinity"]
    healthcheck:
      test: ["CMD", "true"]
      interval: 2s
      timeout: 1s
      retries: 1
      start_period: 0s
    deploy: {}
    volumes: []
    ports: []

  backend:
    environment:
      OLLAMA_BASE_URL: %s
    extra_hosts:
      - "host.docker.internal:host-gateway"
`

// GenerateLocalOllamaOverlay writes the docker-compose.local-ollama.yml overlay file.
func GenerateLocalOllamaOverlay(projectDir, ollamaURL string) error {
	if ollamaURL == "" {
		ollamaURL = "http://host.docker.internal:11434"
	}

	content := fmt.Sprintf(localOllamaOverlayTemplate, ollamaURL)
	path := projectDir + "/docker-compose.local-ollama.yml"

	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write overlay temp: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("rename overlay: %w", err)
	}

	return nil
}

// RemoveLocalOllamaOverlay removes the overlay file if it exists.
func RemoveLocalOllamaOverlay(projectDir string) error {
	path := projectDir + "/docker-compose.local-ollama.yml"
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// --- GPU overlay templates ---

const nvidiaOverlayTemplate = `# docker-compose.gpu-nvidia.yml
# Generated by The Embedinator TUI. Enables NVIDIA GPU for Ollama.
# Do not edit manually. Re-run 'embedinator config' to modify.

services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
`

const amdOverlayTemplate = `# docker-compose.gpu-amd.yml
# Generated by The Embedinator TUI. Enables AMD ROCm GPU for Ollama.
# Do not edit manually. Re-run 'embedinator config' to modify.

services:
  ollama:
    image: ollama/ollama:rocm
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
`

const intelOverlayTemplate = `# docker-compose.gpu-intel.yml
# Generated by The Embedinator TUI. Enables Intel GPU for Ollama (experimental).
# Do not edit manually. Re-run 'embedinator config' to modify.

services:
  ollama:
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - render
`

// GenerateNVIDIAOverlay writes the docker-compose.gpu-nvidia.yml overlay file.
func GenerateNVIDIAOverlay(projectDir string) error {
	return writeGPUOverlay(projectDir, "docker-compose.gpu-nvidia.yml", nvidiaOverlayTemplate)
}

// GenerateAMDOverlay writes the docker-compose.gpu-amd.yml overlay file.
func GenerateAMDOverlay(projectDir string) error {
	return writeGPUOverlay(projectDir, "docker-compose.gpu-amd.yml", amdOverlayTemplate)
}

// GenerateIntelOverlay writes the docker-compose.gpu-intel.yml overlay file.
func GenerateIntelOverlay(projectDir string) error {
	return writeGPUOverlay(projectDir, "docker-compose.gpu-intel.yml", intelOverlayTemplate)
}

// GenerateGPUOverlay generates the appropriate GPU overlay file for the given profile.
// Cleans up overlays from other profiles to avoid conflicts.
func GenerateGPUOverlay(profile, projectDir string) error {
	// Remove all GPU overlays first to avoid stale files.
	for _, f := range []string{"docker-compose.gpu-nvidia.yml", "docker-compose.gpu-amd.yml", "docker-compose.gpu-intel.yml"} {
		path := projectDir + "/" + f
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove old overlay %s: %w", f, err)
		}
	}

	switch profile {
	case "nvidia":
		return GenerateNVIDIAOverlay(projectDir)
	case "amd":
		return GenerateAMDOverlay(projectDir)
	case "intel":
		return GenerateIntelOverlay(projectDir)
	case "none":
		return nil // No overlay needed.
	default:
		return fmt.Errorf("unknown GPU profile: %q", profile)
	}
}

// writeGPUOverlay writes a GPU overlay file atomically.
func writeGPUOverlay(projectDir, filename, content string) error {
	path := projectDir + "/" + filename
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write GPU overlay temp: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("rename GPU overlay: %w", err)
	}
	return nil
}
